### ISSUE TITLE
Erro no require 'rsa'

### ISSUE THREAD

**Issue by leo-souza** [ditointernet/dito-gem#1]
Usando ruby 2.1.3 e rails 4.0.10
Ocorre o seguinte erro na linha 3 da classe Dito::Request
require 'rsa'

``` ruby
(development *=)~/netshowme$ rails c
/home/leo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.0.10/lib/active_support/dependencies.rb:229:in `require': cannot load such file -- rsa (LoadError)
    from /home/leo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.0.10/lib/active_support/dependencies.rb:229:in `block in require'
    from /home/leo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.0.10/lib/active_support/dependencies.rb:214:in `load_dependency'
    from /home/leo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.0.10/lib/active_support/dependencies.rb:229:in `require'
    from /home/leo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/dito-0.0.2/lib/dito/request.rb:3:in `<top (required)>'
```

**Comment by leo-souza** [comment]
sem esse require funcionou aqui
8ccdc2e5c3b08267a985696100e65866ba5cfa75

**Comment by marcosnogueira** [comment]
@leo-souza você consegue conferir se a assinatura para autenticação continuou funcionando normalmente?

**Comment by leo-souza** [comment]
@marcosnogueira eu só consegui testar usando o fork que eu fiz, não rodou usando a gem original, nem o server nem o console. 
Usando meu fork eu fiz todas as chamadas do identify e track.

**Comment by marcosnogueira** [comment]
@leo-souza Removi o require. Parece que realmente ele não era necessário.

Já criei uma nova versão da gem. Instale a partir dela e me diga se funcionou: 0.0.3.

**Comment by leo-souza** [comment]
@marcosnogueira funcionou. valeu
